apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}-filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: filebeat
  version: 8.6.2
{{ .Values.eck | toYaml | indent 2 }}
  config:
    filebeat.inputs:
    - type: filestream
      id: {{ .Release.Name }}-text-logs
      paths:
      - /var/log/**.log

    - type: filestream
      id: {{ .Release.Name }}-json-logs
      paths:
      - /var/log/**.json
      parsers:
      - ndjson:
          add_error_key: true

    - type: filestream
      id: {{ .Release.Name }}-csv-logs
      paths:
      - /var/log/**.csv
      processors:
      - decode_csv_fields:
          fields:
            message: decoded.csv
          separator: ","
          ignore_missing: false
          overwrite_keys: true
          trim_leading_space: false
          fail_on_error: true

  daemonSet:
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0
        containers:
        - name: filebeat
          volumeMounts:
          - name: logs
            mountPath: /var/log
        volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logs