
alert:
  scan_interval: 10s
  scan_window: 2m
  alert_interval: 10m
  allowed_threat_interval: 1s
  score_funcs: |
    - filter:
        term:
          network.transport: ipv6-icmp
      weight: 0.001
    - filter:
        exists:
          field: auditd
      weight: 0.001
    - filter:
        term:
          auditd.data.terminal: cron
      weight: 0.001

mail:
  to: it@example.com
  subject: >-
    Alert: {info.num_hits:apnumber} event(s) detected since {info.scan_len:naturaldelta} ago.
  body: |
    {info.num_hits} event(s) detected between {info.scan_begin} and {info.scan_end}.

    Event sources include:
    {info.sources_list}
