# Source: eck-operator/templates/operator-namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: elastic
  labels:
    name: elastic
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 8.6.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      server.basePath: /es
      server.rewriteBasePath: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  rules:
  - host: rancher.dutnet.local  # hostname to access rancher server
    http:
      paths:
      - path: /es
        pathType: Prefix
        backend:
          service:
            name: elasticsearch-es-http
            port: http
  tls:
  - hosts:
    - rancher.dutnet.local
    secretName: tls-rancher-ingress
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.6.1
  count: 1
  elasticsearchRef:
    name: es
  nodeSets:
  - config:
      server.basePath: /kb
      server.rewriteBasePath: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  rules:
  - host: rancher.dutnet.local  # hostname to access rancher server
    http:
      paths:
      - path: /kb
        pathType: Prefix
        backend:
          service:
            name: kibana-kb-http
            port: http
  tls:
  - hosts:
    - rancher.dutnet.local
    secretName: tls-rancher-ingress
---