# Adapted from https://raw.githubusercontent.com/elastic/cloud-on-k8s/2.6/config/recipes/beats/auditbeat_hosts.yaml
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}-auditbeat
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: auditbeat
  version: 8.5.2
{{ .Values.eck | toYaml | indent 2 }}
  config:
    auditbeat.modules:
    - module: auditd
      audit_rules: |
        -a always,exit -F dir=/mnt/home/ -F perm=rwxa -F key=samba
  daemonSet:
    podTemplate:
      spec:
        hostPID: true  # Required by auditd module
        securityContext:
          runAsUser: 0
        volumes:
        - name: home
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-home
        containers:
        - name: auditbeat
          securityContext:
            capabilities:
              add: ['AUDIT_READ', 'AUDIT_WRITE', 'AUDIT_CONTROL']
          volumeMounts:
          - name: home
            mountPath: "/mnt/home"
            readOnly: true