apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-avahi-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
{{ tpl (.Files.Glob "avahi/*").AsConfig . | indent 2 }}