apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-samba-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
{{ (.Files.Glob "etc-samba/*.*").AsConfig | indent 2 }}