apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "virusalert.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "virusalert.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "virusalert.labels" . | nindent 8 }}
    spec:
      containers:
      - name: virusalert
        image: ajmansfield/virusalert

        env:
        - name: SCAN_INTERVAL
          valueFrom:
            configMapRef:
              name: "{{ .Release.Name }}-alert"
              key: scan_interval
        - name: SCAN_WINDOW
          valueFrom:
            configMapRef:
              name: "{{ .Release.Name }}-alert"
              key: scan_window
        - name: ALERT_INTERVAL
          valueFrom:
            configMapRef:
              name: "{{ .Release.Name }}-alert"
              key: alert_interval
        - name: ALLOWED_THREAT_INTERVAL
          valueFrom:
            configMapRef:
              name: "{{ .Release.Name }}-alert"
              key: allowed_threat_interval
          
        - name: ES_HOSTS
          value: "https://{{ .Values.eck.elasticsearchRef.name }}-es-http.{{ .Values.eck.elasticsearchRef.namespace }}.svc:9200"
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-elastic"
              key: username
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-elastic"
              key: password

        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-smtp"
              key: username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-smtp"
              key: password
        - name: SMTP_HOST
            secretKeyRef:
              name: "{{ .Release.Name }}-smtp"
              key: hostname
        - name: SMTP_PORT
            secretKeyRef:
              name: "{{ .Release.Name }}-smtp"
              key: port
              optional: true
        
        - name: DKIM_DOMAIN
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-dkim"
              key: domain
              optional: true
        - name: DKIM_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-dkim"
              key: key
              optional: true
        - name: DKIM_SELECTOR
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-dkim"
              key: selector
              optional: true

        - name: MAIL_TO
          valueFrom:
            configMapRef:
              name: "{{ .Release.Name }}-mail"
              key: to
        - name: MAIL_SUBJECT
          valueFrom:
            configMapRef:
              name: "{{ .Release.Name }}-mail"
              key: subject
        - name: MAIL_BODY
          valueFrom:
            configMapRef:
              name: "{{ .Release.Name }}-mail"
              key: body
        

