apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "virusalert.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "virusalert.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "virusalert.labels" . | nindent 8 }}
    spec:
      containers:
      - name: virusalert
        image: ajmansfield/virusalert
        imagePullPolicy: Always
        
        env:
        - name: ES_HOSTS
          value: "https://{{ .Values.eck.elasticsearchRef.name }}-es-http.{{ .Values.eck.elasticsearchRef.namespace }}.svc:9200"
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-elastic"
              key: username
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-elastic"
              key: password

        volumeMounts:
        - name: alert
          mountPath: /etc/virusalert/alert
          readOnly: true
        - name: smtp
          mountPath: /etc/virusalert/smtp
          readOnly: true
        - name: dkim
          mountPath: /etc/virusalert/dkim
          readOnly: true
        - name: mail
          mountPath: /etc/virusalert/mail
          readOnly: true
        - name: elasticsearch-certs
          mountPath: /mnt/elastic-internal/elasticsearch-certs
          readOnly: true
        # - mountPath: /mnt/elastic-internal/kibana-certs
        #   name: kibana-certs
        #   readOnly: true

      volumes:
      - name: alert
        configMap:
          name: "{{ .Release.Name }}-alert"
      - name: smtp
        secret:
          secretName: "{{ .Release.Name }}-smtp"
      - name: dkim
        secret:
          secretName: "{{ .Release.Name }}-dkim"
          optional: true
      - name: mail
        configMap:
          name: "{{ .Release.Name }}-mail"
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          optional: false
          secretName: {{ .Release.Name }}-fakebeat-beat-es-ca
      # - name: kibana-certs
      #   secret:
      #     defaultMode: 420
      #     optional: false
      #     secretName: {{ .Release.Name }}-fakebeat-beat-kibana-ca

