apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "virusalert.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "virusalert.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "virusalert.labels" . | nindent 8 }}
    spec:
      containers:
      - name: virusalert
        image: ajmansfield/virusalert
        
        env:
        - name: ES_HOSTS
          value: "https://{{ .Values.eck.elasticsearchRef.name }}-es-http.{{ .Values.eck.elasticsearchRef.namespace }}.svc:9200"
        - name: ES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-elastic"
              key: username
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-elastic"
              key: password

        volumeMounts:
        - name: alert
          path: /etc/virusalert/alert
          readOnly: true
        - name: smtp
          path: /etc/virusalert/smtp
          readOnly: true
        - name: dkim
          path: /etc/virusalert/dkim
          readOnly: true
        - name: mail
          path: /etc/virusalert/mail
          readOnly: true

      volumes:
        - name: alert
          configMap:
            name: "{{ .Release.Name }}-alert"
        - name: smtp
          secret:
            secretName: "{{ .Release.Name }}-smtp"
        - name: dkim
          secret:
            secretName: "{{ .Release.Name }}-dkim"
            optional: true
        - name: mail
          configMap:
            name: "{{ .Release.Name }}-mail"

