{{- $to := .Values.mail.to | required "Email adddress is required." -}}
{{- $subject := .Values.mail.subject | required "Email subject template is required." -}}
{{- $body := .Values.mail.body | required "Email body template is required." -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mail
  namespace: {{ .Release.Namespace }}
  labels: {{- include "virusalert.labels" . | nindent 4 }}
data: {{- .Values.mail | toYaml | nindent 2 }}
