{{- required "Email adddress is required." .Values.mail.to -}}
{{- required "Email subject template is required." .Values.mail.subject -}}
{{- required "Email body template is required." .Values.mail.body -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mail
  namespace: {{ .Release.Namespace }}
  labels: {{- include "virusalert.labels" . | nindent 4 }}
data: {{- .Values.mail | toYaml | nindent 2 }}
