apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smtp
  namespace: {{ .Release.Namespace }}
  labels: {{- include "virusalert.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData: {{- .Values.smtp | toYaml | nindent 2 }}
