{{- $username := .Values.smtp.username | required "SMTP username is required."  -}}
{{- $password := .Values.smtp.password | required "SMTP password is required."  -}}
{{- $hostname := .Values.smtp.hostname | required "SMTP hostname is required."  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-smtp
  namespace: {{ .Release.Namespace }}
  labels: {{- include "virusalert.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData: {{- .Values.smtp | toYaml | nindent 2 }}
