apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: filebeat
  version: 8.6.2
{{ .Values.eck | toYaml | indent 2 }}
  config: {}
  deployment:
    replicas: 0
## for the moment we're using this Beat to get eck-operator grant us some creds
## - elasticsearch CA, in secret "{{ .Release.Name }}-beat-es-ca"
## - a username, "{{ .Release.Namespace }}-{{ .Release.Name }}-beat-user"
## - a password, in secret ""{{ .Release.Name }}-beat-user"