apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: logstash
  version: 8.6.2
  # image: docker.elastic.co/logstash/logstash:8.6.2
  image: docker.elastic.co/logstash/logstash:8.6.2
{{ .Values.eck | toYaml | indent 2 }}
  deployment:
    replicas: 1
    podTemplate:
      spec:
        # serviceAccountName: "{{ .Release.Namespace }}-{{ .Release.Name }}-beat-user"
        # securityContext:
        #   roles:
        #   - name: eck_beat_es_logstash_role
        #     elasticsearch:
        #       cluster:
        #       - monitor
        #       - manage_index_templates
        #       - manage_pipeline
        #       indices:
        #       - names: ["logstash-*"]
        #         privileges:
        #         - auto_configure
        #         - create
        #         - delete
        #         - index
        #         - manage
        #         - read
        #         - write
        initContainers:
        - name: listbot-dl
          image: alpine
          volumeMounts:
          - name: listbot
            mountPath: /etc/listbot
          command:
          - /bin/sh
          - -c
          - |
            set -x
            cd /etc/listbot
            touch cve.yaml
            touch iprep.yaml

            
          # wget https://listbot.sicherheitstacho.eu/cve.yaml.bz2
          # wget https://listbot.sicherheitstacho.eu/iprep.yaml.bz2
          # bunzip2 -f *.bz2
          # head -c 3145728 cve.yaml > cve.yaml
          # head -c 3145728 iprep.yaml > iprep.yaml
          # sed -i '$ d' *.yaml
        
        containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.6.2
          # command: [ "/usr/share/logstash/bin/logstash" ]
          args: [ "--log.level=info" ] 
          # "--node.name", {{ .Values.hostname }}
          # "--config.reload.automatic"
          env:
          - name: MY_EXTIP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
            #TODO some way to get the honeypot's dhcp-obtained IP
          - name: MY_INTIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_HOSTNAME
            value: {{ .Values.hostname }}

          - name: ES_HOSTS
            value: "https://{{ .Values.eck.elasticsearchRef.name }}-es-http.{{ .Values.eck.elasticsearchRef.namespace }}.svc:9200"
          - name: ES_USER
            value: "{{ .Release.Namespace }}-{{ .Release.Name }}-beat-user"
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-beat-user"
                key: "{{ .Release.Namespace }}-{{ .Release.Name }}-beat-user"

          volumeMounts:
          - name: beat-data
            mountPath: /mnt/logstash/data
          
          - name: data
            mountPath: /data
          - name: listbot
            mountPath: /etc/listbot
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: pipeline-volume
            mountPath: /usr/share/logstash/pipeline
          - name: elasticsearch-certs
            mountPath: /etc/logstash/certificates
            readOnly: true

            
          resources:
            limits:
              cpu: 1000m
              memory: 900Mi
            requests:
              cpu: 100m
              memory: 300Mi
            

        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
        - name: listbot
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logstash-listbot

        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-logstash-config
        - name: pipeline-volume
          configMap:
            name: {{ .Release.Name }}-logstash-pipeline
## for the moment we're using this Beat to get eck-operator grant us some creds
## - elasticsearch CA, in secret "{{ .Release.Name }}-beat-es-ca"
## - a username, "{{ .Release.Namespace }}-{{ .Release.Name }}-beat-user"
## - a password, in secret ""{{ .Release.Name }}-beat-user"