{{- $hostname := .Values.hostname | required "Hostname is required." -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-honeypot
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teapot.potLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "teapot.potSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "teapot.potLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Values.networks }}
    spec:
      hostname: {{ .Values.hostname }}
      securityContext:
        fsGroup: 2000
      containers:
        {{- range $behavior := (.Values.behaviorOrder | default (keys .Values.behaviors)) }}
        {{- $template := printf "%v.containers" $behavior -}}
        {{- include $template $ | indent 6 }}
        {{- end }}
      volumes:
        {{- range $behavior := (.Values.behaviorOrder | default (keys .Values.behaviors)) }}
        {{- $template := printf "%v.volumes" $behavior -}}
        {{- include $template $ | indent 6 }}
        {{- end }}
