{{- $hostname := .Values.hostname | required "Hostname is required." -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-honeypot
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teapot.potLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "teapot.potSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "teapot.potLabels" . | nindent 8 }}
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ include "teapot.networkList" $ }}
    spec:
      hostname: {{ .Values.hostname }}
      securityContext:
        fsGroup: 2000
      containers:
        {{- range $behavior := (.Values.behaviors) }}
        {{- $name := $behavior.name }}
        {{- $spec := ( $behavior.spec | default (dict) ) }}
        {{- $data := merge (dict "Name" $name "Spec" $spec) ($) }}
        {{- $template := printf "%v.containers" $name }}
        {{- include $template $data | nindent 6 }}
        {{- end }}
      volumes:
        {{- range $behavior := (.Values.behaviors) }}
        {{- $name := $behavior.name }}
        {{- $spec := ( $behavior.spec | default (dict) ) }}
        {{- $data := merge (dict "Name" $name "Spec" $spec) ($) }}
        {{- $template := printf "%v.volumes" $name }}
        {{- include $template $data | nindent 6 }}
        {{- end }}
