apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-honeypot
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teapot.labels" . | toYaml | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: {{ .Values.networks }}
    spec:
      hostname: {{ .Values.hostname }}
      containers:
        {{- range $behavior, $config := .Values.behaviors }}
        {{- $template := printf "%v.containers" $behavior -}}
        {{- include $template $ | indent 6 }}
        {{- end }}
      volumes:
        {{- range $behavior, $config := .Values.behaviors }}
        {{- $template := printf "%v.volumes" $behavior -}}
        {{- include $template $ | indent 6 }}
        {{- end }}
