{{- range $behavior := (.Values.behaviors) }}
{{- $name := $behavior.name }}
{{- $spec := ( $behavior.spec | default (dict) ) }}
{{- $data := merge (dict "Name" $name "Spec" $spec) ($) }}
{{- $template := printf "%v.extras" $name }}
{{- include $template $data }}
---
{{- end }}