## Source: templates/samba/_mkall.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-listbot-dl
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teapot.logLabels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: listbot-dl
        image: alpine
        volumeMounts:
        - name: listbot
          mountPath: /etc/listbot
        command:
        - /bin/sh
        - -c
        - |
          set -x
          cd /etc/listbot
          wget https://listbot.sicherheitstacho.eu/cve.yaml.bz2
          wget https://listbot.sicherheitstacho.eu/iprep.yaml.bz2
          bunzip2 -f *.bz2
          head -c 3145728 cve.yaml > cve.yaml
          head -c 3145728 iprep.yaml > iprep.yaml
          sed -i '$ d' *.yaml
      volumes:
      - name: listbot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-listbot
      restartPolicy: Never