apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-logstash
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teapot.logLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "teapot.logSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "teapot.logLabels" . | nindent 8 }}
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.6.2
        # command: [ "sleep", "99999" ]
        # args: [ "--log.level=debug" ]
        env:
        - name: ES_HOSTS
          value: "https://{{ .Values.eck.elasticsearchRef.name }}-es-http.{{ .Values.eck.elasticsearchRef.namespace }}.svc:9200"
        {{- if .Values.autoUser }}
        - name: ES_USER
          value: "{{ .Release.Namespace }}-{{ .Release.Name }}-beat-user"
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-beat-user"
              key: "{{ .Release.Namespace }}-{{ .Release.Name }}-beat-user"
        {{- else }}
        - name: ES_USER
          value: "{{ .Values.elasticUser }}"
        - name: ES_PASSWORD
          value: "{{ .Values.elasticPass }}"
        {{- end }}

        - name: MY_EXTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
          #TODO some way to get the honeypot's DHCP-acquired IP
        - name: MY_INTIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_HOSTNAME
          value: {{ .Values.hostname }}

        volumeMounts:
        - name: data
          mountPath: /data
        - name: listbot
          mountPath: /etc/listbot
        - name: config-volume
          mountPath: /usr/share/logstash/config
        - name: pipeline-volume
          mountPath: /usr/share/logstash/pipeline
        - name: elasticsearch-certs
          mountPath: /etc/logstash/certificates
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
      - name: listbot
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-listbot

      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-logstash-config
      - name: pipeline-volume
        configMap:
          name: {{ .Release.Name }}-logstash-pipeline
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          optional: false
          secretName: {{ .Release.Name }}-logstash-beat-es-ca