- pipeline.id: logstash
  path.config: "/usr/share/logstash/config/logstash.conf"
  pipeline.ecs_compatibility: disabled
- pipeline.id: http_input
  path.config: "/usr/share/logstash/config/http_input.conf"
  pipeline.ecs_compatibility: disabled
