apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "lad.labels" . | nindent 4 }}
data:
  .env_config.yaml: |
    STORAGE_DATASOURCE: "es"
    STORAGE_DATASINK: "es"
    ES_QUERY: "*"
    ES_USE_SSL: True
    ES_INPUT_INDEX: ""
    ES_INPUT_INDEX_RAW: "logstash-*,auditbeat-*,filebeat-*,packetbeat-*"
    ES_TARGET_INDEX: "odcs-anomaly-detect-"
    ES_VERSION: 7
    TRAIN_MAX_ENTRIES: 10000
    INFER_ANOMALY_THRESHOLD: 1.3
    INFER_TIME_SPAN: 10
    INFER_LOOPS: 1
    INFER_MAX_ENTRIES: 10000
    PARALLELISM: 6
    SOMPY_TRAIN_ROUGH_LEN: 100
    SOMPY_TRAIN_FINETUNE_LEN: 5
    SOMPY_INIT: "random"
    HOSTNAME_INDEX: "host"
    DATETIME_INDEX: "@timestamp"
    MESSAGE_INDEX: "message"
