apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-lad
  namespace: {{ .Release.Namespace }}
  labels: {{- include "lad.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "lad.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "lad.labels" . | nindent 8 }}
    spec:
      containers:
      - name: lad
        image: ajmansfield/log-anomaly-detector:latest
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        env:
        - name: LAD_ES_ENDPOINT
          value: "https://{{ .Values.eck.elasticsearchRef.name }}-es-http.{{ .Values.eck.elasticsearchRef.namespace }}.svc:9200"
        - name: LAD_ES_USER
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-elastic"
              key: username
        - name: LAD_ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{ .Release.Name }}-elastic"
              key: password
              
        resources:
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - mountPath: /opt/lad-data/models
          name: model-storage
          
        - name: config
          mountPath: /opt/lad-config/
          readOnly: true

        - name: elasticsearch-certs
          mountPath: /etc/elastic/elasticsearch/certs
          readOnly: true

      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-model-storage
      - name: config
        configMap:
          name: {{ .Release.Name }}-config
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          optional: false
          secretName: {{ .Release.Name }}-fakebeat-beat-es-ca
