{{- $source := lookup "v1" "Secret" .Values.elasticUserRef.namespace .Values.elasticUserRef.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-elastic
  namespace: {{ .Release.Namespace }}
  labels: {{- include "lad.labels" . | nindent 4 }}
  annotations:
    source-namespace: {{ .Values.elasticUserRef.namespace }}
    source-secret: {{ .Values.elasticUserRef.name }}
type: {{ $source.type }}
data: {{- $source.data | toYaml | nindent 2 }}
