apiVersion: v1
kind: Namespace
metadata:
  name: samba-honeypot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-pvc
  namespace: samba-honeypot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
  namespace: samba-honeypot
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "mode": "bridge",
      "master": "eno1",
      "ipam": {
        "type": "dhcp",
        "provide": [
          {
            "option": "host-name",
            "value": "fileserver"
          }
        ]
      }
    }'
---
# Configuration for the samba domain member pod.
apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-container-config
  namespace: samba-honeypot
data:
  config.json: |
    {
      "samba-container-config": "v0",
      "configs": {
        "sambadm1": {
          "shares": [
            "share"
          ],
          "globals": [
            "noprinting",
            "sambadm1"
          ],
          "instance_name": "SMBDM1"
        }
      },
      "shares": {
        "share": {
          "options": {
            "path": "/share",
            "read only": "no",
            "guest ok": "yes",
            "create mask": "0755",
            "directory mask": "0755"
          }
        }
      },
      "_NOTE": "Change the security and workgroup keys to match your domain.",
      "globals": {
        "noprinting": {
          "options": {
            "load printers": "no",
            "printing": "bsd",
            "printcap name": "/dev/null",
            "disable spoolss": "yes"
          }
        },
        "sambadm1": {
          "options": {
            "workgroup": "WORKGROUP"
          }
        }
      }
    }
---
# The pod itself.
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: samba-dm-example
  name: samba-dm
  namespace: samba-honeypot
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  shareProcessNamespace: true
  containers:
    - image: quay.io/samba.org/samba-server:latest
      name: smb
      command:
      - "samba-container"
      - "--debug-delay=1"
      - "run"
      - "smbd"
      env:
      - name: SAMBACC_CONFIG
        value: /etc/samba-container/config.json
      - name: SAMBA_CONTAINER_ID
        value: sambadm1
      - name: SAMBACC_VERSION
        value: "0.1"
      - name: HOSTNAME
        value: sambadm1
      ports:
      - containerPort: 445
        hostPort: 455
        protocol: TCP
        name: "smb"
      securityContext:
        allowPrivilegeEscalation: true
      volumeMounts:
      - mountPath: "/share"
        name: samba-sharedir
      - mountPath: "/etc/samba-container"
        name: samba-container-config
      - mountPath: "/var/lib/samba"
        name: samba-state-dir
      - mountPath: "/run/samba/winbindd"
        name: samba-sockets-dir
    - image: quay.io/samba.org/samba-server:latest
      name: winbind
      command:
      - "samba-container"
      - "run"
      - "winbindd"
      env:
      - name: SAMBACC_VERSION
        value: "0.1"
      - name: SAMBACC_CONFIG
        value: /etc/samba-container/config.json
      - name: SAMBA_CONTAINER_ID
        value: sambadm1
      - name: HOSTNAME
        value: sambadm1
      securityContext:
        allowPrivilegeEscalation: true
      volumeMounts:
      - mountPath: "/etc/samba-container"
        name: samba-container-config
      - mountPath: "/var/lib/samba"
        name: samba-state-dir
      - mountPath: "/run/samba/winbindd"
        name: samba-sockets-dir
  initContainers:
    - image: quay.io/samba.org/samba-server:latest
      name: init
      args:
      - "init"
      env:
      - name: SAMBACC_VERSION
        value: "0.1"
      - name: SAMBACC_CONFIG
        value: /etc/samba-container/config.json
      - name: SAMBA_CONTAINER_ID
        value: sambadm1
      - name: HOSTNAME
        value: sambadm1
      securityContext:
        allowPrivilegeEscalation: true
      volumeMounts:
      - mountPath: "/etc/samba-container"
        name: samba-container-config
      - mountPath: "/var/lib/samba"
        name: samba-state-dir
  volumes:
  - configMap:
      name: samba-container-config
    name: samba-container-config
  - emptyDir:
      medium: Memory
    name: samba-sockets-dir
  - emptyDir: {}
    name: samba-state-dir
# Comment out the section below to skip using a PVC for the share
  - persistentVolumeClaim:
      claimName: samba-pvc
    name: samba-sharedir
# Uncomment the section below to use an empty dir for the share
#  - emptyDir:
#      medium: Memory
#    name: samba-sharedir