apiVersion: v1
kind: Namespace
metadata:
  name: samba-honeypot
  labels:
    app: samba-honeypot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-pvc
  namespace: samba-honeypot
  labels:
    app: samba-honeypot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
# Configuration for the samba domain member pod.
apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-container-config
  namespace: samba-honeypot
  labels:
    app: samba-honeypot
data:
  config.json: |
    {
      "samba-container-config": "v0",
      "configs": {
        "sambasrv": {
          "shares": [
            "public"
          ],
          "globals": [
            "default"
          ],
          "instance_name": "SAMBASRV"
        }
      },
      "globals": {
        "default": {
          "options": {
            "workgroup": "WORKGROUP",
            "server string": "Samba Server",
            "server role": "standalone server",
            "guest account": "guest",
            "map to guest": "Bad User",
            "bind interfaces only": "yes",
            "interfaces": "lo net1",
            "wins support": "yes",
            "browseable": "yes"
          }
        }
      },
      "shares": {
        "public": {
          "options": {
            "comment": "All the files.",
            "path": "/share",
            "public": "yes",
            "browseable": "yes",
            "guest only": "yes",
            "writeable": "yes",
            "force create mode": "0666",
            "force directory mode": "0777"
          }
        }
      },
      "users": {
        "all_entries": [
          {
            "name": "guest",
            "password": "password"
          }
        ]
      },
      "_footer": 1
    }
---
# DHCP interface configuration script
apiVersion: v1
kind: ConfigMap
metadata:
  name: udhcpc-scripts
  namespace: samba-honeypot
  labels:
    app: samba-honeypot
data:
  default.script: |
    #!/bin/sh
    [ -n "$1" ] || { echo "Error: should be called from udhcpc"; exit 1; }

    NETMASK=""
    [ -n "$subnet" ] && NETMASK="netmask $subnet"
    BROADCAST="broadcast +"
    [ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"

    case "$1" in
      deconfig)
        echo "Setting IP address 0.0.0.0 on $interface"
        ifconfig $interface 0.0.0.0
        ;;

      renew|bound)
        echo "Setting IP address $ip on $interface"
        ifconfig $interface $ip $NETMASK $BROADCAST
    esac

    exit 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: samba-honeypot
  labels:
    app: samba-honeypot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba-honeypot
  template:
    metadata:
      labels:
        app: samba-honeypot
      annotations:
        k8s.v1.cni.cncf.io/networks: honeynet/macvlan
    spec:
      shareProcessNamespace: true
      containers:
        - image: quay.io/samba.org/samba-server:latest
          name: smb
          command: ["samba-container", "run", "smbd"]
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
          - mountPath: "/share"
            name: samba-sharedir
          - mountPath: "/etc/samba-container"
            name: samba-container-config
          - mountPath: "/var/lib/samba"
            name: samba-state-dir
          - mountPath: "/run/samba/winbindd"
            name: samba-sockets-dir

        - image: quay.io/samba.org/samba-server:latest
          name: winbind
          command: ["samba-container", "run", "winbindd"]
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
          - mountPath: "/etc/samba-container"
            name: samba-container-config
          - mountPath: "/var/lib/samba"
            name: samba-state-dir
          - mountPath: "/run/samba/winbindd"
            name: samba-sockets-dir

        - image: busybox
          name: dhcp-client
          command: [
            "udhcpc",
            "-i", "net1", # Interface to use
            "-B", # Request broadcast replies (so everyone sees us)
            "-T", "5", # Pause between packets
            "-R", # Release IP on exit
            "-f", # Run in foreground
            "-a", # Validate offerred address with ARP ping (so everyone sees us)
            "-O", "12", # request Host Name
            "-O", "15", # request Domain Name
            "-O", "42", # request NTP Servers
            "-O", "119", # request Doman Search
            "-O", "120", # request SIP Servers
            "-x", "hostname:sambasrv", # provide option 22
            # "-x", "lease:60", # request short 60-second lease
            "-F", "sambasrv", # Ask server to update DNS mapping for "fileserver"
            "-V", "Microsloth", # Vendor identifier (instead of udhcp)
          ]
          volumeMounts:
          - mountPath: "/usr/share/udhcpc/"
            name: udhcpc-scripts
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add: ["NET_BIND_SERVICE", "NET_BROADCAST", "NET_ADMIN"]
        
        - image: jonasped/wsdd
          name: wsdd
          env:
          - name: WSDD_ARGS
            value: "--interface net1 --hostname SAMBASRV --workgroup WORKGROUP"
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add: ["NET_BIND_SERVICE", "NET_BROADCAST"]
            
      initContainers:
        - image: quay.io/samba.org/samba-server:latest
          name: init
          args: ["init"]
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
          - mountPath: "/etc/samba-container"
            name: samba-container-config
          - mountPath: "/var/lib/samba"
            name: samba-state-dir
      volumes:
      - configMap:
          name: samba-container-config
        name: samba-container-config
      - emptyDir:
          medium: Memory
        name: samba-sockets-dir
      - emptyDir: {}
        name: samba-state-dir
    # Comment out the section below to skip using a PVC for the share
      - persistentVolumeClaim:
          claimName: samba-pvc
        name: samba-sharedir
    # Uncomment the section below to use an empty dir for the share
    #  - emptyDir:
    #      medium: Memory
    #    name: samba-sharedir

      - name: udhcpc-scripts
        configMap:
          name: udhcpc-scripts
          defaultMode: 0744