

hostname: joes-samsung-galaxy-phone

networks: honeynet/macvlan

behaviors:
  default: {}
  adbhoney: {}
  dhcp: {}
  endlessh: {}


# ECK reference info to give to file/auditbeat
eck:
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic
  kibanaRef:
    name: kibana
    namespace: elastic