

# hostname: honeypot.example.com

networks: honeynet/macvlan

behaviors:
- name: default
- name: dhcp
#   spec:
#     hostname: honeypot.example.com
#     vendor: example-vendor
- name: packetbeat
# - name: samba
#   spec:
#     workgroup: QUINKAP
# - name: honeytrap
# - name: ciscoasa
# - name: log4pot
# - name: citrixhoneypot
# - name: adbhoney
# - name: tanner
# - name: cowrie
# - name: glutton
# - name: endlessh
# - name: ddospot
# - name: conpot-default
# - name: conpot-iec104
# - name: conpot-guardian-ast
# - name: conpot-ipmi
# - name: conpot-kamstrup-382
# - name: wordpot
# - name: ipphoney
# - name: dionaea
# - name: medpot
# - name: dicompot
# - name: heralding
# - name: sentrypeer
# - name: mailoney
# - name: hellpot
# - name: redishoneypot
# - name: elasticpot
# - name: honeypots


# ECK reference info to give to file/auditbeat
eck:
  elasticsearchRef:
    name: elastic
    namespace: elastic
  kibanaRef:
    name: elastic
    namespace: elastic

logstashUserRef:
  name: elastic-logstash-user
  namespace: elastic