

#hostname: 

networks: honeynet/macvlan

behaviors:
  default: {}
  dhcp: {}
  #   #hostname:
  #   #vendor: 
  packetbeat: {}
  # samba: {}
  #   # workgroup: QUINKAP
  # honeytrap: {}
  # ciscoasa: {}
  # log4pot: {}
  # citrixhoneypot: {}
  # adbhoney: {}
  # tanner: {}
  # cowrie: {}
  # glutton: {}
  # endlessh: {}
  # ddospot: {}
  # conpot-default: {}
  # conpot-iec104: {}
  # conpot-guardian-ast: {}
  # conpot-ipmi: {}
  # conpot-kamstrup-382: {}
  # wordpot: {}
  # ipphoney: {}
  # dionaea: {}
  # medpot: {}
  # dicompot: {}
  # heralding: {}
  # sentrypeer: {}
  # mailoney: {}
  # hellpot: {}
  # redishoneypot: {}
  # elasticpot: {}
  # honeypots: {}

behaviorOrder:
- default
- dhcp
- packetbeat
# - samba
# - honeytrap
# - ciscoasa
# - log4pot
# - citrixhoneypot
# - adbhoney
# - tanner
# - cowrie
# - glutton
# - endlessh
# - ddospot
# - conpot-default
# - conpot-iec104
# - conpot-guardian-ast
# - conpot-ipmi
# - conpot-kamstrup-382
# - wordpot
# - ipphoney
# - dionaea
# - medpot
# - dicompot
# - heralding
# - sentrypeer
# - mailoney
# - hellpot
# - redishoneypot
# - elasticpot
# - honeypots


# ECK reference info to give to file/auditbeat
eck:
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic
  kibanaRef:
    name: kibana
    namespace: elastic

logstashUserRef:
  name: logstash-user
  namespace: elastic