

hostname: joes-samsung-galaxy-phone

networks: honeynet/macvlan

behaviors:
  default: {}
  dhcp:
    hostname: joes-samsung-galaxy-phone
    vendor: android
  packetbeat: {}
  samba:
    workgroup: QUINKAP
  honeytrap: {}
  ciscoasa: {}
  log4pot: {}
  citrixhoneypot: {}
  adbhoney: {}
  tanner: {}
  cowrie: {}
  glutton: {}
  endlessh: {}
  ddospot: {}
  conpot-default: {}
  conpot-iec104: {}
  conpot-guardian-ast: {}
  conpot-ipmi: {}
  conpot-kamstrup-382: {}
  wordpot: {}
  ipphoney: {}
  dionaea: {}
  medpot: {}
  dicompot: {}
  heralding: {}
  sentrypeer: {}
  mailoney: {}
  hellpot: {}
  redishoneypot: {}
  elasticpot: {}
  honeypots: {}

behaviorOrder:
- default
- dhcp
- packetbeat
- samba
- honeytrap
- ciscoasa
- log4pot
- citrixhoneypot
- adbhoney
- tanner
- cowrie
- glutton
- endlessh
- ddospot
- conpot-default
- conpot-iec104
- conpot-guardian-ast
- conpot-ipmi
- conpot-kamstrup-382
- wordpot
- ipphoney
- dionaea
- medpot
- dicompot
- heralding
- sentrypeer
- mailoney
- hellpot
- redishoneypot
- elasticpot
- honeypots


# ECK reference info to give to file/auditbeat
eck:
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic
  kibanaRef:
    name: kibana
    namespace: elastic
autoUser: false
# TODO: helm can read the values of secrets at install-time
# use this to copy the secret into the target namespace and then use that
elasticUser: logstash
elasticPass: "JIi8qtZTZJxWP45W"