

hostname: joes-samsung-galaxy-phone

networks: honeynet/macvlan

behaviors:
  default: {}
  packetbeat: {}
  adbhoney: {}
  dhcp: {}
  endlessh: {}


# ECK reference info to give to file/auditbeat
eck:
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic
  kibanaRef:
    name: kibana
    namespace: elastic
autoUser: false
# TODO: helm can read the values of secrets at install-time
# use this to copy the secret into the target namespace and then use that
elasticUser: logstash
elasticPass: "JIi8qtZTZJxWP45W"