apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kb
  namespace: {{ .Release.Namespace }}
  labels: {{- include "elastic.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/issuer: elastic
    cert-manager.io/issuer-kind: Issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - http:
      paths:
      - path: /kibana(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-kb-http
            port:
              name: https
  tls:
  - secretName: tls-{{ .Release.Name }}-kb-ingress