apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-lad-role
  namespace: {{ .Release.Namespace }}
  labels: {{- include "elastic.labels" . | nindent 4 }}
stringData:
  roles.yml: |-
    lad_role:
      indices:
      - names: ["**"]
        privileges:
        - read