apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-logstash-user
  namespace: {{ .Release.Namespace }}
  labels: {{- include "elastic.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: logstash
  password: {{ randAlphaNum 32 }}
  roles: logstash_role