apiVersion: v1
kind: Secret
metadata:
  name: logstash-role
  namespace: {{ .Release.Namespace }}
  labels: {{- include "elastic.labels" . | nindent 4 }}
stringData:
  roles.yml: |-
    logstash_role:
      cluster:
      - monitor
      - manage_index_templates
      - manage_pipeline
      indices:
      - names: ["logstash-*"]
        privileges:
        - auto_configure
        - create
        - delete
        - index
        - manage
        - read
        - write