apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-virusalert-role
  namespace: {{ .Release.Namespace }}
  labels: {{- include "elastic.labels" . | nindent 4 }}
stringData:
  roles.yml: |-
    virusalert_role:
      indices:
      - names: ["logstash-*","auditbeat-*","filebeat-*","packetbeat-*"]
        privileges:
        - read