## Source: templates/samba/_cfg_avahi.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-samba-avahi
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teapot.potLabels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/samba/avahi/*").AsConfig | indent 2 }}