## Source: templates/samba/_mkall.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-samba-mkall
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teapot.potLabels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
      - name: mkall
        image: busybox
        command: ["/opt/mkall.sh","/opt/file_list.txt","/opt/dir_list.txt","/shares"]
        volumeMounts:
        - name: data
          mountPath: /shares
          subPath: samba/shares
        - name: mkall
          mountPath: /opt
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-data
      - name: mkall
        configMap:
          name: {{ .Release.Name }}-samba-mkall
          defaultMode: 0700
      restartPolicy: Never