apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "system.labels" . | nindent 4 }}
spec:
  version: 8.6.1
  auth:
    fileRealm:
    - secretName: {{ .Release.Name }}-logstash-user
    roles:
    - secretName: {{ .Release.Name }}-logstash-role
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false