# TODO auto-generate this secret:
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-virusalert-user
  namespace: {{ .Release.Namespace }}
  labels: {{- include "system.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: virusalert
  password: {{ randAlphaNum 32 }}
  roles: virusalert_role